### ISSUE TITLE
Actions Issue

### ISSUE THREAD

**Issue by kassemKu** [Torrix/laravel-ui-uikit#3]
First Thank you for this great Integration,
after a fresh installation, the hover action (on username) in the top navbar doesn't work!!,

**Comment by mattfletcher** [comment]
@kassemKu thank you. I will take a look into this as soon as I can. I also need to update it to the latest point release of UIkit.

**Comment by kassemKu** [comment]
OK, I disabled the cache, and it works fine now, thank you again, by the way, I am UIKIT Lover,

**Comment by mattfletcher** [comment]
Ah okay, glad to hear it. Enjoy using UIkit and this integration of it.

**Comment by kassemKu** [comment]
thank you for this great job

**Comment by mattfletcher** [comment]
I can't take the credit. The integration is only a tiny bit of code - the real great work is all down to YOOtheme!

Please do get in touch if you release anything using it, I'd love to see how it gets used.

**Comment by kassemKu** [comment]
OK, I'll do, I use UIKIT in most of my projects, I like how it supported RTL, and it's component's system, grid, actions, how to manage JS events, really UIKIT is greater css3 Framework today....

I do not know why it is not popular enough ??

**Comment by kassemKu** [comment]
![Screen Shot 2019-11-11 at 2 12 24 AM](https://user-images.githubusercontent.com/32443422/68553354-0f97d380-0429-11ea-98ac-8474bf548a20.png)
![Screen Shot 2019-11-11 at 2 14 20 AM](https://user-images.githubusercontent.com/32443422/68553355-11fa2d80-0429-11ea-8a3f-da7b9db3c24f.png)

**Comment by kassemKu** [comment]
UIKIT in use :)

**Comment by kassemKu** [comment]
can we use an aliases class name? in the next version
`uk-text-center`
replaced with 
`uk-tc`**as example** OR something like this

hope to find vertical,  horizontal ( padding, margin) padding-X, margin-Y

**Comment by mattfletcher** [comment]
@kassemKu that would be a question for the UIkit developers. This integration doesn't change anything about how it works.

**Comment by kassemKu** [comment]
Excuse me, I thought you one of UIKIT developers

**Comment by mattfletcher** [comment]
No not at all, just a fan of Laravel and UIkit!

**Comment by kassemKu** [comment]
anyway, you do a great job,
 what about UIKIT react, like material-ui, Or UIKIT vue like vuetify??
 I Don't find someone does this job??
